# Generated by Django 3.2.5 on 2021-07-08 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.IntegerField()),
                ('final_price', models.IntegerField()),
                ('time_stamp', models.TimeField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafe.orders')),
                ('ueser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafe.user')),
            ],
        ),
        migrations.DeleteModel(
            name='Receits',
        ),
    ]
